name: Deploy Development

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.73.166
        port: 22
        username: root
        password: 3142mdpl
        script: |
          cd /aino/testingweb/
          git pull origin main
